import type { EditorThemeClasses } from 'lexical'

export const lexicalTheme: EditorThemeClasses = {
  paragraph: 'text-tx-main leading-[1.8] mb-2',
  heading: {
    h1: 'text-tx-main text-2xl font-bold mb-4 mt-6',
    h2: 'text-tx-main text-xl font-semibold mb-3 mt-5',
    h3: 'text-tx-main text-lg font-medium mb-2 mt-4',
  },
  text: {
    bold: 'font-bold text-tx-main',
    italic: 'italic',
    code: 'bg-bg-active text-accent-main px-1.5 py-0.5 rounded text-[13px] font-mono',
    underline: 'underline',
    strikethrough: 'line-through opacity-60',
    highlight: 'bg-accent-main/20 text-accent-main px-0.5 rounded-sm',
  },
  list: {
    ul: 'editor-ul list-disc mb-2 text-tx-main',
    ol: 'editor-ol list-decimal mb-2 text-tx-main',
    listitem: 'mb-1 editor-listitem',
    checklist: 'list-none editor-checklist mb-2',
    listitemChecked: 'line-through opacity-50 relative pl-6 list-none editor-listitem editor-listitem-checked',
    listitemUnchecked: 'relative pl-6 list-none editor-listitem editor-listitem-unchecked',
    nested: {
      listitem: 'list-none',
    },
  },
  code: 'bg-bg-popover text-tx-main block p-4 rounded-lg font-mono text-[13px] mb-4 border border-border-subtle overflow-x-auto relative',
  codeHighlight: {
    keyword: 'text-accent-main',
    string: 'text-[#C4A46C]',
    comment: 'text-tx-faint italic',
    function: 'text-[#fde047]',
    number: 'text-[#B5CEA8]',
    property: 'text-[#fdba74]',
    operator: 'text-tx-muted',
    punctuation: 'text-tx-muted',
    variable: 'text-tx-main',
    atrule: 'text-accent-main',
    attr: 'text-[#fdba74]',
    'attr-value': 'text-[#C4A46C]',
    builtin: 'text-[#D4A959]',
    char: 'text-[#C4A46C]',
    class: 'text-[#D4A959]',
    constant: 'text-accent-main',
    deleted: 'text-[#ff6b6b]',
    important: 'text-[#ff6b6b] font-bold',
    inserted: 'text-accent-main',
    prolog: 'text-tx-faint',
    regex: 'text-[#e06c75]',
    selector: 'text-[#CC8B6E]',
    tag: 'text-[#CC8B6E]',
  },
  link: 'text-[#5BA4A4] underline cursor-pointer hover:text-[#7ec8c8]',
  quote: 'border-l-4 border-[#5BA4A4]/40 pl-4 italic text-tx-muted mb-4',
  table: 'editor-table border-collapse w-full my-2 mb-4',
  tableRow: 'editor-table-row',
  tableCell: 'editor-table-cell border border-border-strong px-3 py-1.5 text-tx-muted text-sm min-w-[60px] align-top',
  tableCellHeader: 'editor-table-cell-header border border-border-strong px-3 py-1.5 text-tx-main text-sm font-medium bg-bg-hover align-top',
  tableSelection: 'bg-accent-main/[0.06]',
  tableCellSelected: 'bg-accent-main/[0.06]',
  tableCellPrimarySelected: 'bg-accent-main/[0.04]',
  tableCellEditing: '',
  hashtag: 'inline-flex items-center justify-center bg-accent-main/15 text-accent-main px-1.5 mx-0.5 rounded-md text-[0.9em] font-medium cursor-pointer hover:bg-accent-main/25 transition-colors align-baseline leading-none py-[0.15em]',
}
