import type { EditorThemeClasses } from 'lexical'

export const lexicalTheme: EditorThemeClasses = {
  paragraph: 'text-[#e1e4e8] leading-[1.8] mb-2',
  heading: {
    h1: 'text-[#fff] text-2xl font-bold mb-4 mt-6',
    h2: 'text-[#eee] text-xl font-semibold mb-3 mt-5',
    h3: 'text-[#ddd] text-lg font-medium mb-2 mt-4',
  },
  text: {
    bold: 'font-bold text-[#fff]',
    italic: 'italic',
    code: 'bg-white/10 text-[#5eead4] px-1.5 py-0.5 rounded text-[13px] font-mono',
    underline: 'underline',
    strikethrough: 'line-through opacity-60',
    highlight: 'bg-[#5eead4]/20 text-[#5eead4] px-0.5 rounded-sm',
  },
  list: {
    ul: 'list-disc pl-6 mb-2 text-[#e1e4e8]',
    ol: 'list-decimal pl-6 mb-2 text-[#e1e4e8]',
    listitem: 'mb-1 editor-listitem',
    checklist: 'pl-0 list-none editor-checklist',
    listitemChecked: 'line-through opacity-50 relative pl-7 list-none editor-listitem editor-listitem-checked',
    listitemUnchecked: 'relative pl-7 list-none editor-listitem editor-listitem-unchecked',
    nested: {
      listitem: 'list-none',
    },
  },
  code: 'bg-[#1e1e1e] text-[#ccc] block p-4 rounded-lg font-mono text-[13px] mb-4 border border-white/8 overflow-x-auto relative',
  codeHighlight: {
    keyword: 'text-[#5eead4]',
    string: 'text-[#C4A46C]',
    comment: 'text-[#555] italic',
    function: 'text-[#fde047]',
    number: 'text-[#B5CEA8]',
    property: 'text-[#fdba74]',
    operator: 'text-[#888]',
    punctuation: 'text-[#888]',
    variable: 'text-[#ccc]',
    atrule: 'text-[#5eead4]',
    attr: 'text-[#fdba74]',
    'attr-value': 'text-[#C4A46C]',
    builtin: 'text-[#D4A959]',
    char: 'text-[#C4A46C]',
    class: 'text-[#D4A959]',
    constant: 'text-[#5eead4]',
    deleted: 'text-[#ff6b6b]',
    important: 'text-[#ff6b6b] font-bold',
    inserted: 'text-[#5eead4]',
    prolog: 'text-[#555]',
    regex: 'text-[#e06c75]',
    selector: 'text-[#CC8B6E]',
    tag: 'text-[#CC8B6E]',
  },
  link: 'text-[#5BA4A4] underline cursor-pointer hover:text-[#7ec8c8]',
  quote: 'border-l-4 border-[#5BA4A4]/40 pl-4 italic text-[#999] mb-4',
  table: 'editor-table border-collapse w-full my-2 mb-4',
  tableRow: 'editor-table-row',
  tableCell: 'editor-table-cell border border-white/[0.06] px-3 py-1.5 text-[#b0b0b0] text-sm min-w-[60px] align-top',
  tableCellHeader: 'editor-table-cell-header border border-white/[0.06] px-3 py-1.5 text-[#d0d0d0] text-sm font-medium bg-white/[0.03] align-top',
  tableSelection: 'bg-[#5eead4]/[0.06]',
  tableCellSelected: 'bg-[#5eead4]/[0.06]',
  tableCellPrimarySelected: 'bg-[#5eead4]/[0.04]',
  tableCellEditing: '',
}
